version: "3.8"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PG_DB=url_shortener
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_HOST=db

volumes:
  db_data:
